### ISSUE TITLE
Useful documentation

### ISSUE THREAD

**Issue by chris-pearce** [fedordead/vanilla-ui#2]
@davislurve @bnhovde I started a repo documenting the accessibility specs for the type of components that will exist in this repo, see: https://github.com/chris-pearce/accessibility-specs.

**Comment by bnhovde** [comment]
Excellent stuff, I like where this is going. If we manage to build a library of generic, functional &  accessible UI components then I'd use them in all my work.

I've been using the fedordead "organisation" as the primary source for the vanilla-ui repo and then forked a version to my individual account to actually work on it. What do you guys think of that approach?

**Comment by chris-pearce** [comment]
> If we manage to build a library of generic, functional & accessible UI components then I'd use them in all my work.

For sure, its badly needed—I've searched over the years for something like this and nothing ever delivered. It's a very sweet project.

> I've been using the fedordead "organisation" as the primary source for the vanilla-ui repo and then forked a version to my individual account to actually work on it. What do you guys think of that approach?

That's the way I was gonna do it :+1:.

**Comment by chris-pearce** [comment]
I'll close this.
