### ISSUE TITLE
Discuss the function names for "open/show" and "close/hide"

### ISSUE THREAD

**Issue by chris-pearce** [fedordead/vanilla-ui#28]
If you look at the [Dialog](https://github.com/fedordead/vanilla-ui/blob/master/src/components/dialog/dialog.js) component we have these functions:

``` js
openDialog()
showDialog()
```

``` js
closeDialog()
hideDialog()
```

I find these function names too similar and it always causes confusion for me when I read the code. 

Be good to discuss alternatives.

**Comment by DaveOrDead** [comment]
Yeah they are really similar and I'm not happy with them either.

We probably don't actually need both.  Maybe just stick with open and close.  The only thing is the `openDialog()` is quite a chunker

**Comment by chris-pearce** [comment]
I don't mind if a function is a bit large when it's for a very specific purpose—I'd rather that than breaking it up for the sake of it.

**Comment by DaveOrDead** [comment]
Sweet, I addressed it in PR: https://github.com/fedordead/vanilla-ui/pull/30

**Comment by chris-pearce** [comment]
OK cool, closing this then.
