### ISSUE TITLE
Component structure

### ISSUE THREAD

**Issue by bnhovde** [fedordead/vanilla-ui#4]
I've had a look at other similar libraries out there for inspiration. I particularly like the approach the umbrellaJS people have taken: Each component has it's own folder with documentation and test.

have a look at the below link for an example.

https://github.com/umbrellajs/umbrella/tree/master/src

**Comment by chris-pearce** [comment]
I like having each component's files in its own folder including a README.

**Comment by DaveOrDead** [comment]
Seems like a good way to structure it to me. Agree with the readme too
