### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by chris-pearce** [fedordead/vanilla-ui#7]
Do we do:
- IE 10/11
- All evergreen browsers:
  - Edge
  - Chrome
  - Safari
  - Firefox

Even no IE 10?

**Comment by chris-pearce** [comment]
http://caniuse.com/#search=date

**Comment by bnhovde** [comment]
This is always a tricky one. I haven't had that many quarrels with IE10 personally (outside of some weird flexbox oddities), but I'd be happy to take your advice on this one.

At least any compiled JS should run fine down to IE9. (Well.. in theory)

**Comment by DaveOrDead** [comment]
id say we include 10 to start but if IE bugs are taking ages to fix for it then we reconsider?

**Comment by chris-pearce** [comment]
> id say we include 10 to start but if IE bugs are taking ages to fix for it then we reconsider?

I'm happy with that.

@bnhovde I agree with IE 10 problems being mainly related to Flexbox.

**Comment by bnhovde** [comment]
Excellent. I think we can close this issue then since we're all in agreement on IE10.
